routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');
Route::get('home', 'HomeController@index');

// Auth::routes();

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::group(['middleware' => 'auth'], function () {
    Route::get('password', 'PasswordController@change')->name('password.change');
    Route::put('password', 'PasswordController@update')->name('password.update');
});

Route::group(['middleware' => 'admin'], function(){
  Route::put('password/{id}', 'PasswordController@updateAdmin')->name('password.updateAdmin');
  Route::Resource('data-guru', 'TeacherController');
  Route::get('api/data-guru', 'TeacherController@apiDataGuru')->name('api.data-guru');
  Route::get('api/data-guru-indo', 'TeacherController@apiDataGuruIndo')->name('api.data-guru-indo');
  Route::get('api/data-guru-inggris', 'TeacherController@apiDataGuruInggris')->name('api.data-guru-inggris');
  Route::get('api/data-guru-mtk', 'TeacherController@apiDataGuruMtk')->name('api.data-guru-mtk');
  Route::get('api/data-guru-ipa', 'TeacherController@apiDataGuruIpa')->name('api.data-guru-ipa');
  Route::Resource('data-siswa', 'StudentController');
  Route::get('api/data-siswa', 'StudentController@apiDataSiswa')->name('api.data-siswa');
  Route::get('api/data-mapel', 'SubjectController@apiDataMapel')->name('api.data-mapel');
});

Route::group(['middleware' => 'admin'||'teacher'], function(){
  Route::Resource('soal','QuestionController');
  Route::get('api/soal', 'QuestionController@apiSoal')->name('api.soal');
  Route::Resource('hasil-ujian', 'ResultController');
  Route::get('hasil-ujian/{id}/pdf/IX-A', 'ResultController@pdf_a')->name('hasil-ujian.IX-A');
  Route::get('hasil-ujian/{id}/pdf/IX-B', 'ResultController@pdf_b')->name('hasil-ujian.IX-B');
  Route::get('hasil-ujian/{id}/pdf/IX-C', 'ResultController@pdf_c')->name('hasil-ujian.IX-C');
  Route::get('hasil-ujian/{id}/pdf/IX-D', 'ResultController@pdf_d')->name('hasil-ujian.IX-D');

});

Route::group(['middleware' => 'teacher'], function(){
  Route::Resource('ujian', 'MakeTestController');
  Route::get('api/ujian', 'MakeTestController@apiUjian')->name('api.ujian');
});


Route::group(['middleware' => 'student'], function(){
  Route::get('api/ujian-siswa', 'StudentTestController@apiUjianSiswa')->name('api.ujian-siswa');
  Route::get('ujian-siswa', 'StudentTestController@index')->name('ujian-siswa.index');
  Route::post('ujian-siswa/verif-token', 'StudentTestController@veriftoken')->name('ujian-siswa.verif');
  Route::get('ujian-siswa/{encode_id}', 'StudentTestController@show')->name('ujian-siswa.show');
  Route::post('ujian-siswa/{id}', 'StudentTestController@store')->name('ujian-siswa.store');
  Route::get('nilai-siswa/{id}', 'StudentTestController@result')->name('ujian-siswa.result');
  Route::get('hasil-ujian-siswa', 'StudentTestController@resultAll')->name('ujian-siswa.result-all');
  Route::get('hasil-ujian-siswa/pdf', 'StudentTestController@pdf')->name('ujian-siswa.pdf');
});

app/Question.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
  protected $fillable = [
    'user_id',
    'subject_teacher',
    'question',
    'a',
    'b',
    'c',
    'd',
    'correct_answer'
  ];

  public function user()
  {
    return $this->belongsTo(User::class);
  }
}

app/Http/Controllers/QuestionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;
use Illuminate\Support\Facades\Auth;
use App\Question;
use App\User;
use DB;

class QuestionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

      if (Auth::user()->role == 3) {
        $questions = DB::table('questions')
                      ->select('questions.id', 'questions.user_id', 'users.name','questions.subject',
                                DB::raw('substr(question, 1, 30) as question'),
                                'questions.a', 'questions.b', 'questions.c', 'questions.d', 'questions.correct_answer',
                                'questions.created_at', 'questions.updated_at')
                      ->join('users', 'users.id', '=', 'questions.user_id')
                      ->get();
        return view('questions.question', compact('questions'));

      } else {
        $id = Auth::id();
        $questions = DB::table('questions')
                      ->select('questions.id', 'questions.user_id', 'users.name','questions.subject',
                                DB::raw('substr(question, 1, 30) as question'),
                                'questions.a', 'questions.b', 'questions.c', 'questions.d', 'questions.correct_answer',
                                'questions.created_at', 'questions.updated_at')
                      ->join('users', 'users.id', '=', 'questions.user_id')
                      ->where('users.id', $id)
                      ->get();
        return view('questions.question', compact('questions'));
      }

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      return view('questions.create-question');
      // $users_indo = User::select('users.id', 'users.name', 'teachers.subject')
      //               ->join('teachers', 'users.id', '=', 'teachers.user_id')
      //               ->where('subject', '=', 'Bahasa Indonesia')
      //               ->get();
      //
      // $users_inggris = User::select('users.id', 'users.name', 'teachers.subject')
      //                   ->join('teachers', 'users.id', '=', 'teachers.user_id')
      //                   ->where('subject', '=', 'Bahasa Inggris')
      //                   ->get();
      //
      // $users_mtk = User::select('users.id', 'users.name', 'teachers.subject')
      //                   ->join('teachers', 'users.id', '=', 'teachers.user_id')
      //                   ->where('subject', '=', 'Matematika')
      //                   ->get();
      //
      // $users_ipa = User::select('users.id', 'users.name', 'teachers.subject')
      //                   ->join('teachers', 'users.id', '=', 'teachers.user_id')
      //                   ->where('subject', '=', 'Ilmu Pengetahuan Alam')
      //                   ->get();

        // return view('users.create-question',[
        //   'users_indo'=>$users_indo,
        //   'users_inggris'=>$users_inggris,
        //   'users_mtk'=>$users_mtk,
        //   'users_ipa'=>$users_ipa
        // ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
          $question = new Question();
          $question->user_id = $request->user_id;
          $question->subject = $request->subject;
          $question->question = $request->question;
          $question->a = $request->a;
          $question->b = $request->b;
          $question->c = $request->c;
          $question->d = $request->d;
          $question->correct_answer = $request->correct_answer;
          $question->save();

          return redirect()->route('soal.index')->with('alert-success', 'Data Berhasil Dibuat.');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

      $data = Question::findOrFail($id);

      return view('questions.edit-question', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // dd($id);

      $question = Question::findOrFail($id);
      $question->user_id = $request->user_id;
      $question->subject = $request->subject;
      $question->question = $request->question;
      $question->a = $request->a;
      $question->b = $request->b;
      $question->c = $request->c;
      $question->d = $request->d;
      $question->correct_answer = $request->correct_answer;
      $question->save();

      return redirect()->route('soal.index')->with('alert-success', 'Data Berhasil Diubah.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Question::destroy($id);
        return redirect()->route('soal.index')->with('alert-success', 'Data Berhasil Dihapus.');
    }

    public function apiSoal()
    {
      if (Auth::user()->role == 3) {
        $questions = DB::table('questions')
                      ->select('questions.id', 'questions.user_id', 'users.name','questions.subject',
                                DB::raw('substr(question, 1, 30) as question'),
                                'questions.a', 'questions.b', 'questions.c', 'questions.d', 'questions.correct_answer',
                                'questions.created_at', 'questions.updated_at')
                      ->join('users', 'users.id', '=', 'questions.user_id')
                      ->get();

                      return Datatables::of($questions)
                            ->addColumn('action', function($questions){
                              $route_edit = route('soal.edit', $questions->id);
                                return '<a href="'.$route_edit.'" class="btn btn-primary btn-xs"><i class="far fa-edit"></i> Edit</a> ' .
                                       '<a onclick="deleteData('. $questions->id .')" class="btn btn-danger btn-xs"><i class="far fa-trash-alt"></i> Delete</a> ';
                            })
                            ->editColumn('question', function ($questions){
                              return '{!!'.$questions->question.'!!}';
                            })
                            ->make(true);



      } else {
        $id = Auth::id();
        $questions = DB::table('questions')
                      ->select('questions.id', 'questions.user_id', 'users.name','questions.subject',
                                DB::raw('substr(question, 1, 30) as question'),
                                'questions.a', 'questions.b', 'questions.c', 'questions.d', 'questions.correct_answer',
                                'questions.created_at', 'questions.updated_at')
                      ->join('users', 'users.id', '=', 'questions.user_id')
                      ->where('users.id', $id)
                      ->get();

                      return Datatables::of($questions)
                            ->addColumn('action', function($questions){
                              $route_edit = route('soal.edit', $questions->id);
                                return '<a href="'.$route_edit.'" class="btn btn-primary btn-xs"><i class="far fa-edit"></i> Edit</a> ' .
                                       '<a onclick="deleteData('. $questions->id .')" class="btn btn-danger btn-xs"><i class="far fa-trash-alt"></i> Delete</a> ';
                            })
                            ->editColumn('question', function ($questions){
                              return '{!!'.$questions->question.'!!}';
                            })
                            ->make(true);
    }
  }

}

resources/views/questions/create-question.blade.php
@extends('layouts.master')

@section('content')

  <div class="container-fluid">
    <div class="row">
      <div class="col-md-2">
        <div class="list-group">
          <a href="{{ route('home')}}" class="list-group-item list-group-item-action">
            <i class="far fa-user-circle"></i> <b>Dashboard</b>
          </a>
          @if(Auth::user()->isAdmin())
            <a href="{{ route('data-siswa.index') }}" class="list-group-item list-group-item-action"><i class="fas fa-list-alt"></i> <b>Data Siswa</b></a>
            <a href="{{ route('data-guru.index') }}" class="list-group-item list-group-item-action"><i class="fas fa-list-alt"></i> <b>Data Guru</b></a>
          @endif

          @if(Auth::user()->isAdmin() || Auth::user()->isTeacher())
            <a href="{{ route('soal.index') }}" class="list-group-item list-group-item-action active"><i class="fas fa-list-alt"></i> <b>Bank Soal</b></a>
            @if (Auth::user()->isTeacher())
              <a href="{{ route('ujian.index') }}" class="list-group-item list-group-item-action"><i class="fas fa-list-alt"></i> <b>Ujian</b></a>
            @endif
            <a href="{{ route('hasil-ujian.index') }}" class="list-group-item list-group-item-action"><i class="fas fa-list-alt"></i> <b>Hasil Ujian</b></a>
          @endif

        </div>
      </div>

      <div class="col-md-9">
        <div class="panel panel-default">
          <!-- Default panel contents -->
          <div class="panel-heading">
            <h4>Input Soal</h4>
          </div>

          <div class="panel-body">
            <form method="post" action="{{ route('soal.store') }}" class="form-horizontal" data-toggle="validator" enctype="multipart/form-data">
                {{ csrf_field() }} {{ method_field('POST') }}


                @if (Auth::user()->isTeacher())
                  <input type="hidden" name="user_id" value="{{Auth::user()->id}}">
                  <div class="form-group">
                      <label for="subject" class="col-md-2 control-label">Mapel</label>
                      <div class="col-md-6">
                        <input class="form-control" type="text" name="subject" value="{{Auth::user()->teacher->subject}}" readonly>
                        <span class="help-block with-errors"></span>
                      </div>
                  </div>

                  <div class="form-group" id="name">
                      <label for="name" class="col-md-2 control-label">Guru</label>
                      <div class="col-md-6">
                        <input class="form-control" type="text" name="name" value="{{Auth::user()->name}}" readonly>
                        <span class="help-block with-errors"></span>
                      </div>
                  </div>
                @endif

                @if (Auth::user()->isAdmin())
                  <div class="form-group">
                      <label for="subject" class="col-md-2 control-label">Mapel</label>
                      <div class="col-md-6">
                        <select class="form-control" id="subject" name="subject" required>
                            <option disabled value="" selected>-</option>
                            <option value="Bahasa Indonesia">Bahasa Indonesia</option>
                            <option value="Bahasa Inggris">Bahasa Inggris</option>
                            <option value="Matematika">Matematika</option>
                            <option value="Ilmu Pengetahuan Alam">Ilmu Pengetahuan Alam</option>
                          </select>
                          <span class="help-block with-errors"></span>
                      </div>
                  </div>

                  <div class="form-group">
                      <label for="user_id" class="col-md-2 control-label">Guru</label>
                      <div class="col-md-6">
                        <select class="form-control" id="user_id" name="user_id" required>
                            <option disabled value="" selected>-</option>
                          </select>
                          <span class="help-block with-errors"></span>
                      </div>
                  </div>
                @endif

                    <div class="form-group">
                        <label for="question" class="col-md-2 control-label">Teks Soal</label>
                        <div class="col-md-9">
                          <textarea id="question" class="form-control" name="question" rows="4" cols="50" required></textarea>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="a" class="col-md-2 control-label">Jawaban a</label>
                        <div class="col-md-9">
                          <textarea id="a" class="form-control" name="a" rows="4" cols="50" required></textarea>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="b" class="col-md-2 control-label">Jawaban b</label>
                        <div class="col-md-9">
                          <textarea id="b" class="form-control" name="b" rows="4" cols="50" required></textarea>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="c" class="col-md-2 control-label">Jawaban c</label>
                        <div class="col-md-9">
                          <textarea id="c" class="form-control" name="c" rows="4" cols="50" required></textarea>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="d" class="col-md-2 control-label">Jawaban d</label>
                        <div class="col-md-9">
                          <textarea id="d" class="form-control" name="d" rows="4" cols="50" required></textarea>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="correct_answer" class="col-md-2 control-label" required>Kunci Jawaban</label>
                        <div class="col-md-2">
                          <select class="form-control" id="correct_answer" name="correct_answer" required>
                              <option disabled value="" selected>-</option>
                              <option value="a">a</option>
                              <option value="b">b</option>
                              <option value="c">c</option>
                              <option value="d">d</option>
                            </select>
                            <span class="help-block with-errors"></span>
                        </div>
                    </div>

                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary btn-save">Submit</button>
                    <a href="{{ route('soal.index') }}" type="button" class="btn btn-default">Kembali</a>
                </div>

            </form>
      </div>
      </div>
      </div>
    </div>
    <br>
   <br>
  <br>
@endsection

@section('script')

  <script type="text/javascript">

    $('#question').ckeditor({
      filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
      filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token=' + $("input[name=_token]").val(),
      filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
      filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token=' + $("input[name=_token]").val()
    });

    $('#a').ckeditor({
      filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
      filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token=' + $("input[name=_token]").val(),
      filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
      filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token=' + $("input[name=_token]").val()
    });

    $('#b').ckeditor({
      filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
      filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token=' + $("input[name=_token]").val(),
      filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
      filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token=' + $("input[name=_token]").val()
    });

    $('#c').ckeditor({
      filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
      filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token=' + $("input[name=_token]").val(),
      filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
      filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token=' + $("input[name=_token]").val()
    });

    $('#d').ckeditor({
      filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
      filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token=' + $("input[name=_token]").val(),
      filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
      filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token=' + $("input[name=_token]").val()
    });




            $('#subject').on('change',function(){
                var selectedVal = $('#subject option:selected').text();

                if (selectedVal == 'Bahasa Indonesia') {
                  $.ajax({
                    url: "{{ url('api/data-guru-indo') }}",
                    type: "GET",
                    dataType: "JSON",
                    success: function(data){
                      $('#user_id').empty();
                      $('#user_id').append('<option disabled selected>-</option>');
                      $.each(data, function(key, val){
                          $('#user_id').append('<option value="'+ val.id +'">'+ val.name +'</option>');
                        });
                    }
                  });

                } else if (selectedVal == 'Bahasa Inggris') {
                  $.ajax({
                    url: "{{ url('api/data-guru-inggris') }}",
                    type: "GET",
                    dataType: "JSON",
                    success: function(data){
                      $('#user_id').empty();
                      $('#user_id').append('<option disabled selected>-</option>');
                      $.each(data, function(key, val){
                          $('#user_id').append('<option value="'+ val.id +'">'+ val.name +'</option>');
                        });
                    }
                  });

                }else if (selectedVal == 'Matematika') {
                  $.ajax({
                    url: "{{ url('api/data-guru-mtk') }}",
                    type: "GET",
                    dataType: "JSON",
                    success: function(data){
                      $('#user_id').empty();
                      $('#user_id').append('<option disabled selected>-</option>');
                      $.each(data, function(key, val){
                          $('#user_id').append('<option value="'+ val.id +'">'+ val.name +'</option>');
                        });
                    }
                  });
                }else {
                  $.ajax({
                    url: "{{ url('api/data-guru-ipa') }}",
                    type: "GET",
                    dataType: "JSON",
                    success: function(data){
                      $('#user_id').empty();
                      $('#user_id').append('<option disabled selected>-</option>');
                      $.each(data, function(key, val){
                          $('#user_id').append('<option value="'+ val.id +'">'+ val.name +'</option>');
                        });
                    }
                  });
                }
            });
    </script>


  </script>
@endsection

resources/views/questions/question.blade.php
@extends('layouts.master')

@section('content')

  <div class="container-fluid">
    <div class="row">
      <div class="col-md-2">
        <div class="list-group">
          <a href="{{ route('home')}}" class="list-group-item list-group-item-action">
            <i class="far fa-user-circle"></i> <b>Dashboard</b>
          </a>
          @if(Auth::user()->isAdmin())
            <a href="{{ route('data-siswa.index') }}" class="list-group-item list-group-item-action"><i class="fas fa-list-alt"></i> <b>Data Siswa</b></a>
            <a href="{{ route('data-guru.index') }}" class="list-group-item list-group-item-action"><i class="fas fa-list-alt"></i> <b>Data Guru</b></a>
          @endif

          @if(Auth::user()->isAdmin() || Auth::user()->isTeacher())
            <a href="{{ route('soal.index') }}" class="list-group-item list-group-item-action active"><i class="fas fa-list-alt"></i> <b>Bank Soal</b></a>
            @if (Auth::user()->isTeacher())
              <a href="{{ route('ujian.index') }}" class="list-group-item list-group-item-action"><i class="fas fa-list-alt"></i> <b>Ujian</b></a>
            @endif
            <a href="{{ route('hasil-ujian.index') }}" class="list-group-item list-group-item-action"><i class="fas fa-list-alt"></i> <b>Hasil Ujian</b></a>
          @endif

        </div>
      </div>

      <div class="col-md-9">
        <div class="panel panel-default">
          <!-- Default panel contents -->
          <div class="panel-heading">
            <h4>Data Soal
              <a href="{{ route('soal.create') }}" class="btn btn-primary pull-right" style="margin-top: -9px;"><i class="fas fa-plus"></i> Tambah Data </a>
            </h4>
          </div>
          <div class="panel-body">
            @if(Session::has('alert-danger'))
					    <div class="alert alert-danger">
				            {{ Session::get('alert-danger') }}
				        </div>
					@endif
          <!-- Table -->
          <div class="table-responsive">
            <table id="question-table" class="table table-striped table-bordered table-hover">
              <thead>
                <tr>
                  <th width="30">No</th>
                  <th>Soal</th>
                  <th>Mapel</th>
                  <th>Guru</th>
                  <th>Action</th>
                  </tr>
                </thead>
                {{-- <tbody></tbody> --}}
                  @php
                    $i=1;
                  @endphp
                  @foreach($questions as $question)
      						<tr>
      							<td>{{$i}}</td>
      							<td>{!!$question->question!!}</td>
      							<td>{{$question->subject}}</td>
      							<td>{{$question->name}}</td>
      							<td>
                      <a href="{{ route('soal.edit', $question->id) }}" class="btn btn-primary btn-xs"><i class="far fa-edit"></i>Edit</a>
                      <a onclick="deleteData({{$question->id}})" class="btn btn-danger btn-xs"><i class="far fa-trash-alt"></i>Delete</a>
      							</td>
      						</tr>
                  @php
                    $i++;
                  @endphp
      						@endforeach

              </table>
          </div>

          </div>
        </div>
        </div>
        </div>
      </div>
      <br>
     <br>
    <br>
  @endsection


@section('script')

  <script type="text/javascript">
  // var table = $('#question-table').DataTable({
  //                 processing: true,
  //                 serverSide: true,
  //                 ajax: "{{ route('api.soal') }}",
  //                 columns: [
  //                   {data: 'id', name: 'id'},
  //                   {data: 'question', name: 'question'},
  //                   {data: 'subject', name: 'subject'},
  //                   {data: 'name', name: 'name'},
  //                   {data: 'action', name: 'action', orderable: false, searchable: false}
  //                 ]
  //               });

      $(document).ready( function () {
        $('#question-table').DataTable();
      });

      function deleteData(id){
          var csrf_token = $('meta[name="csrf-token"]').attr('content');
          swal({
              title: 'Are you sure?',
              text: "You won't be able to revert this!",
              type: 'warning',
              showCancelButton: true,
              cancelButtonColor: '#d33',
              confirmButtonColor: '#3085d6',
              confirmButtonText: 'Yes, delete it!'
          }).then(function () {
              $.ajax({
                  url : "{{ url('soal') }}" + '/' + id,
                  type : "POST",
                  data : {'_method' : 'DELETE', '_token' : csrf_token},
                  success : function(data) {
                      location.reload();
                      swal({
                          title: 'Success!',
                          text: data.message,
                          type: 'success',
                          timer: '1500'
                      })
                  },
                  error : function () {
                      swal({
                          title: 'Oops...',
                          text: data.message,
                          type: 'error',
                          timer: '1500'
                      })
                  }
              });
          });
        }

  </script>
@endsection