routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');
Route::get('home', 'HomeController@index');

// Auth::routes();

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::group(['middleware' => 'auth'], function () {
    Route::get('password', 'PasswordController@change')->name('password.change');
    Route::put('password', 'PasswordController@update')->name('password.update');
});

Route::group(['middleware' => 'admin'], function(){
  Route::put('password/{id}', 'PasswordController@updateAdmin')->name('password.updateAdmin');
  Route::Resource('data-guru', 'TeacherController');
  Route::get('api/data-guru', 'TeacherController@apiDataGuru')->name('api.data-guru');
  Route::get('api/data-guru-indo', 'TeacherController@apiDataGuruIndo')->name('api.data-guru-indo');
  Route::get('api/data-guru-inggris', 'TeacherController@apiDataGuruInggris')->name('api.data-guru-inggris');
  Route::get('api/data-guru-mtk', 'TeacherController@apiDataGuruMtk')->name('api.data-guru-mtk');
  Route::get('api/data-guru-ipa', 'TeacherController@apiDataGuruIpa')->name('api.data-guru-ipa');
  Route::Resource('data-siswa', 'StudentController');
  Route::get('api/data-siswa', 'StudentController@apiDataSiswa')->name('api.data-siswa');
  Route::get('api/data-mapel', 'SubjectController@apiDataMapel')->name('api.data-mapel');
});

Route::group(['middleware' => 'admin'||'teacher'], function(){
  Route::Resource('soal','QuestionController');
  Route::get('api/soal', 'QuestionController@apiSoal')->name('api.soal');
  Route::Resource('hasil-ujian', 'ResultController');
  Route::get('hasil-ujian/{id}/pdf/IX-A', 'ResultController@pdf_a')->name('hasil-ujian.IX-A');
  Route::get('hasil-ujian/{id}/pdf/IX-B', 'ResultController@pdf_b')->name('hasil-ujian.IX-B');
  Route::get('hasil-ujian/{id}/pdf/IX-C', 'ResultController@pdf_c')->name('hasil-ujian.IX-C');
  Route::get('hasil-ujian/{id}/pdf/IX-D', 'ResultController@pdf_d')->name('hasil-ujian.IX-D');

});

Route::group(['middleware' => 'teacher'], function(){
  Route::Resource('ujian', 'MakeTestController');
  Route::get('api/ujian', 'MakeTestController@apiUjian')->name('api.ujian');
});


Route::group(['middleware' => 'student'], function(){
  Route::get('api/ujian-siswa', 'StudentTestController@apiUjianSiswa')->name('api.ujian-siswa');
  Route::get('ujian-siswa', 'StudentTestController@index')->name('ujian-siswa.index');
  Route::post('ujian-siswa/verif-token', 'StudentTestController@veriftoken')->name('ujian-siswa.verif');
  Route::get('ujian-siswa/{encode_id}', 'StudentTestController@show')->name('ujian-siswa.show');
  Route::post('ujian-siswa/{id}', 'StudentTestController@store')->name('ujian-siswa.store');
  Route::get('nilai-siswa/{id}', 'StudentTestController@result')->name('ujian-siswa.result');
  Route::get('hasil-ujian-siswa', 'StudentTestController@resultAll')->name('ujian-siswa.result-all');
  Route::get('hasil-ujian-siswa/pdf', 'StudentTestController@pdf')->name('ujian-siswa.pdf');
});

app/Result.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Result extends Model
{
  protected $fillable = [
    'test_id',
    'user_id',
    'class',
    'true',
    'false',
    'value',
    'status'
  ];

  public function user()
  {
    return $this->belongsTo(User::class);
  }

  public function test()
  {
    return $this->belongsTo(Test::class);
  }

}

app/Http/Controllers/ResultController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Result;
use App\Answer;
use App\Test;
use App\User;
use PDF;

class ResultController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      if (Auth::user()->role == 3) {
        $tests = Test::All();
        return view('results.result', compact('tests'));
      } else {
        $user_id = Auth::user()->id;
        $tests = Test::where('user_id', $user_id)->get();
        return view('results.result', compact('tests'));
      }


    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $test_id = $id;

      $test = Test::findorfail($id);
      $test = Test::where('id', $test_id)->first();

      $max_a = Result::where('test_id', $test_id)->where('class', 'IX-A')->max('value');
      $min_a = Result::where('test_id', $test_id)->where('class', 'IX-A')->min('value');
      $avg_a = Result::where('test_id', $test_id)->where('class', 'IX-A')->avg('value');

      $max_b = Result::where('test_id', $test_id)->where('class', 'IX-B')->max('value');
      $min_b = Result::where('test_id', $test_id)->where('class', 'IX-B')->min('value');
      $avg_b = Result::where('test_id', $test_id)->where('class', 'IX-B')->avg('value');

      $max_c = Result::where('test_id', $test_id)->where('class', 'IX-C')->max('value');
      $min_c = Result::where('test_id', $test_id)->where('class', 'IX-C')->min('value');
      $avg_c = Result::where('test_id', $test_id)->where('class', 'IX-C')->avg('value');

      $max_d = Result::where('test_id', $test_id)->where('class', 'IX-D')->max('value');
      $min_d = Result::where('test_id', $test_id)->where('class', 'IX-D')->min('value');
      $avg_d = Result::where('test_id', $test_id)->where('class', 'IX-D')->avg('value');

      $data_a = array(
        'name' => $test->user->name,
        'subject' => $test->subject,
        'subject_test' => $test->subject_test,
        'time' => $test->time,
        'start' => $test->start,
        'num_questions' => $test->num_questions,
        'max' => $max_a,
        'min' => $min_a,
        'avg' => $avg_a
      );

      $data_b = array(
        'name' => $test->user->name,
        'subject' => $test->subject,
        'subject_test' => $test->subject_test,
        'time' => $test->time,
        'start' => $test->start,
        'num_questions' => $test->num_questions,
        'max' => $max_b,
        'min' => $min_b,
        'avg' => $avg_b
      );

      $data_c = array(
        'name' => $test->user->name,
        'subject' => $test->subject,
        'subject_test' => $test->subject_test,
        'time' => $test->time,
        'start' => $test->start,
        'num_questions' => $test->num_questions,
        'max' => $max_c,
        'min' => $min_c,
        'avg' => $avg_c
      );

      $data_d = array(
        'name' => $test->user->name,
        'subject' => $test->subject,
        'subject_test' => $test->subject_test,
        'time' => $test->time,
        'start' => $test->start,
        'num_questions' => $test->num_questions,
        'max' => $max_d,
        'min' => $min_d,
        'avg' => $avg_d
      );


      $IX_A = Result::where('test_id', $test_id)
                    ->where('class', 'IX-A')
                    ->get();

      $IX_B = Result::where('test_id', $test_id)
                    ->where('class', 'IX-B')
                    ->get();

      $IX_C = Result::where('test_id', $test_id)
                    ->where('class', 'IX-C')
                    ->get();

      $IX_D = Result::where('test_id', $test_id)
                    ->where('class', 'IX-D')
                    ->get();

      $result = array(
                      'IX_A' => $IX_A,
                      'IX_B' => $IX_B,
                      'IX_C' => $IX_C,
                      'IX_D' => $IX_D,
                    );

        return view('results.show')->with(compact('test_id','result', 'data_a', 'data_b', 'data_c', 'data_d'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      $result = Result::findOrFail($id);
      $user_id = $result->user_id;
      $test_id = $result->test_id;

      $answer = Answer::where('test_id', $test_id)
                      ->where('user_id', $user_id)
                      ->get();

      $count = count($answer);

      for ($i=0; $i < $count; $i++) {
        $answer[$i]->delete();
      }

      Result::destroy($id);
    }


    public function pdf_a($id)
    {
      $test_id = $id;
      $test = Test::where('id', $test_id)->first();

      $max_a = Result::where('test_id', $test_id)->where('class', 'IX-A')->max('value');
      $min_a = Result::where('test_id', $test_id)->where('class', 'IX-A')->min('value');
      $avg_a = Result::where('test_id', $test_id)->where('class', 'IX-A')->avg('value');

      $data_a = array(
        'name' => $test->user->name,
        'subject' => $test->subject,
        'subject_test' => $test->subject_test,
        'time' => $test->time,
        'start' => $test->start,
        'num_questions' => $test->num_questions,
        'max' => $max_a,
        'min' => $min_a,
        'avg' => $avg_a
      );

      $results = Result::select('results.test_id', 'users.name', 'results.class', 'results.true', 'results.false', 'results.value')
                    ->where('test_id', $test_id)
                    ->where('class', 'IX-A')
                    ->leftJoin('users', 'users.id', '=', 'results.user_id')
                    ->orderBy('name', 'asc')
                    ->get();

      $subject_test = $test->subject_test;
      $start = $test->start;
      $teacher = $test->user->name;
      $name = $subject_test.'_'.$teacher.'_'.$start.'_'.'IX-A.pdf';
      $pdf = PDF::loadView('results.pdf-ix-a',compact('results', 'data_a'));
      return $pdf->download($name);

    }

    public function pdf_b($id)
    {
      $test_id = $id;
      $test = Test::where('id', $test_id)->first();

      $max_b = Result::where('test_id', $test_id)->where('class', 'IX-B')->max('value');
      $min_b = Result::where('test_id', $test_id)->where('class', 'IX-B')->min('value');
      $avg_b = Result::where('test_id', $test_id)->where('class', 'IX-B')->avg('value');

      $data_b = array(
        'name' => $test->user->name,
        'subject' => $test->subject,
        'subject_test' => $test->subject_test,
        'time' => $test->time,
        'start' => $test->start,
        'num_questions' => $test->num_questions,
        'max' => $max_b,
        'min' => $min_b,
        'avg' => $avg_b
      );

      $results = Result::select('results.test_id', 'users.name', 'results.class', 'results.true', 'results.false', 'results.value')
                    ->where('test_id', $test_id)
                    ->where('class', 'IX-B')
                    ->leftJoin('users', 'users.id', '=', 'results.user_id')
                    ->orderBy('name', 'asc')
                    ->get();

      $subject_test = $test->subject_test;
      $start = $test->start;
      $teacher = $test->user->name;
      $name = $subject_test.'_'.$teacher.'_'.$start.'_'.'IX-B.pdf';
      $pdf = PDF::loadView('results.pdf-ix-b',compact('results', 'data_b'));
      return $pdf->download($name);

    }

    public function pdf_c($id)
    {
      $test_id = $id;
      $test = Test::where('id', $test_id)->first();

      $max_c = Result::where('test_id', $test_id)->where('class', 'IX-C')->max('value');
      $min_c = Result::where('test_id', $test_id)->where('class', 'IX-C')->min('value');
      $avg_c = Result::where('test_id', $test_id)->where('class', 'IX-C')->avg('value');

      $data_c = array(
        'name' => $test->user->name,
        'subject' => $test->subject,
        'subject_test' => $test->subject_test,
        'time' => $test->time,
        'start' => $test->start,
        'num_questions' => $test->num_questions,
        'max' => $max_c,
        'min' => $min_c,
        'avg' => $avg_c
      );

      $results = Result::select('results.test_id', 'users.name', 'results.class', 'results.true', 'results.false', 'results.value')
                    ->where('test_id', $test_id)
                    ->where('class', 'IX-C')
                    ->leftJoin('users', 'users.id', '=', 'results.user_id')
                    ->orderBy('name', 'asc')
                    ->get();
      // return view('results.pdf-ix-c',compact('results', 'data_c'));
      $subject_test = $test->subject_test;
      $start = $test->start;
      $teacher = $test->user->name;
      $name = $subject_test.'_'.$teacher.'_'.$start.'_'.'IX-C.pdf';
      $pdf = PDF::loadView('results.pdf-ix-c',compact('results', 'data_c'));
      return $pdf->download($name);
    }

    public function pdf_d($id)
    {
      $test_id = $id;
      $test = Test::where('id', $test_id)->first();

resources/views/results/IX-B.blade.php
<div id='IX-B' class="datakelas panel-body">
  <div class="col-md-12 alert alert-warning">
    <div class="col-md-6">
      <table class="table table-bordered" style="margin-bottom: 20px">
        <tbody>
          <tr>
            <td>Mata Pelajaran</td>
            <td>{{$data_b['subject']}}</td>
          </tr>
          <tr>
            <td>Nama Guru</td>
            <td>{{$data_b['name']}}</td>
          </tr>
          <tr>
            <td>Nama Ujian</td>
            <td>{{$data_b['subject_test']}}</td>
          </tr>
          <tr>
            <td>Tanggal Ujian</td>
            <td>{{$data_b['start']}}</td>
          </tr>
          <tr>
            <td>Waktu</td>
            <td>{{$data_b['time']}} menit</td>
          </tr>
        </tbody>
      </table>
    </div>

    <div class="col-md-6">
      <table class="table table-bordered" style="margin-bottom: 20px">
        <tbody>
          <tr>
            <td>Jumlah Soal</td>
            <td>{{$data_b['num_questions']}}</td>
          </tr>
          <tr>
            <td>Tertinggi</td>
            <td>{{$data_b['max']}}</td>
          </tr>
          <tr>
            <td>Terendah</td>
            <td>{{$data_b['min']}}</td>
          </tr>
          <tr>
            <td>Rata-rata</td>
            <td>{{$data_b['avg']}}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <!-- Table -->
  <div class="col-md-12 table-responsive">
    <table id="IX_B-table" class="table table-striped table-bordered table-hover">
      <thead>
        <tr>
          <th width="30">No</th>
          <th>Nama Siswa</th>
          <th>Kelas</th>
          <th>Jumlah Benar</th>
          <th>Jumlah Salah</th>
          <th>Nilai</th>
          <th>Action</th>
          </tr>
      </thead>
      @php
        $i=1;
      @endphp
      @foreach ($result['IX_B'] as $IX_B)
        <tr id ="item{{$IX_B->id}}">
          <td>{{$i}}</td>
          <td>{{$IX_B->user->name}}</td>
          <td>{{$IX_B->class}}</td>
          <td>{{$IX_B->true}}</td>
          <td>{{$IX_B->false}}</td>
          <td>{{$IX_B->value}}</td>
          <td><a onclick="deleteData({{$IX_B->id}})"  class="btn btn-danger btn-xs"><i class="fas fa-times-circle"></i> Batalkan Ujian</a></td>
        </tr>
        @php
          $i++;
        @endphp
      @endforeach
    </table>
  </div>

</div>

resources/views/results/result.blade.php
@extends('layouts.master')

@section('content')

  <div class="container-fluid">
    <div class="row">
      <div class="col-md-2">
        <div class="list-group">
          <a href="{{ route('home')}}" class="list-group-item list-group-item-action">
            <i class="far fa-user-circle"></i> <b>Dashboard</b>
          </a>
          @if(Auth::user()->isAdmin())
            <a href="{{ route('data-siswa.index') }}" class="list-group-item list-group-item-action"><i class="fas fa-list-alt "></i> <b>Data Siswa</b></a>
            <a href="{{ route('data-guru.index') }}" class="list-group-item list-group-item-action"><i class="fas fa-list-alt"></i> <b>Data Guru</b></a>
          @endif

          @if(Auth::user()->isAdmin() || Auth::user()->isTeacher())
            <a href="{{ route('soal.index') }}" class="list-group-item list-group-item-action"><i class="fas fa-list-alt"></i> <b>Bank Soal</b></a>
            @if (Auth::user()->isTeacher())
              <a href="{{ route('ujian.index') }}" class="list-group-item list-group-item-action"><i class="fas fa-list-alt"></i> <b>Ujian</b></a>
            @endif
            <a href="{{ route('hasil-ujian.index') }}" class="list-group-item list-group-item-action active"><i class="fas fa-list-alt"></i> <b>Hasil Ujian</b></a>
          @endif

        </div>
      </div>

      <div class="col-md-9">
        <div class="panel panel-default">
          <!-- Default panel contents -->
          <div class="panel-heading">
            <h4>Daftar Hasil Ujian / Tes</h4>
          </div>
          <div class="panel-body">
          <!-- Table -->
          <div class="table-responsive">
            <table id="result-table" class="table table-striped table-bordered table-hover">
              <thead>
                <tr>
                  <th width="30">No</th>
                  <th>Nama Tes</th>
                  <th>Guru</th>
                  <th>Mapel</th>
                  <th>Jumlah Soal</th>
                  <th>Waktu</th>
                  <th>Action</th>
                  </tr>
              </thead>
              @php
                $i=1;
              @endphp
              @foreach ($tests as $test)
                <tr>
                  <td>{{$i}}</td>
                  <td>{{$test->subject_test}}</td>
                  <td>{{$test->user->name}}</td>
                  <td>{{$test->subject}}</td>
                  <td>{{$test->num_questions}}</td>
                  <td>{{$test->time}} menit</td>
                  <td><a href="{{ route('hasil-ujian.show', $test->id) }}" class="btn btn-primary btn-sm"><i class="fas fa-eye"></i> Lihat Hasil</a></td>
                </tr>
                @php
                  $i++;
                @endphp
              @endforeach
            </table>
          </div>

        </div>
      </div>
      </div>
      </div>
    </div>
    <br>
   <br>
  <br>
@endsection


@section('script')

    <script type="text/javascript">
      var table = $('#result-table').DataTable({
                      processing: true
                    });

      </script>
@endsection

resources/views/results/show.blade.php
@extends('layouts.master')

@section('content')

  <div class="container-fluid">
    <div class="row">
      <div class="col-md-2">
        <div class="list-group">
          <a href="{{ route('home')}}" class="list-group-item list-group-item-action">
            <i class="far fa-user-circle"></i> <b>Dashboard</b>
          </a>
          @if(Auth::user()->isAdmin())
            <a href="{{ route('data-siswa.index') }}" class="list-group-item list-group-item-action"><i class="fas fa-list-alt "></i> <b>Data Siswa</b></a>
            <a href="{{ route('data-guru.index') }}" class="list-group-item list-group-item-action"><i class="fas fa-list-alt"></i> <b>Data Guru</b></a>
          @endif

          @if(Auth::user()->isAdmin() || Auth::user()->isTeacher())
            <a href="{{ route('soal.index') }}" class="list-group-item list-group-item-action"><i class="fas fa-list-alt"></i> <b>Bank Soal</b></a>
            @if (Auth::user()->isTeacher())
              <a href="{{ route('ujian.index') }}" class="list-group-item list-group-item-action"><i class="fas fa-list-alt"></i> <b>Ujian</b></a>
            @endif
            <a href="{{ route('hasil-ujian.index') }}" class="list-group-item list-group-item-action active"><i class="fas fa-list-alt"></i> <b>Hasil Ujian</b></a>
          @endif

        </div>
      </div>

      <div class="col-md-9">
        <div class="panel panel-default">
          <!-- Default panel contents -->
          <div class="panel-heading">
            <h4>Daftar Hasil Ujian / Tes</h4>
          </div>

          <div class="panel panel-default">
            <div class="panel-body">
              <h5><b>KELAS :</b></h5>

                <select id='select_class' class="input-sm" name="">
                  <option value="A">IX-A</option>
                  <option value="B">IX-B</option>
                  <option value="C">IX-C</option>
                  <option value="D">IX-D</option>
                </select>

                <a href="{{route('hasil-ujian.IX-D', $test_id)}}" class="btn btn-primary btn-sm pull-right" style="margin-top: -9px;"><i class="fas fa-file-pdf"></i> IX - D </a>&nbsp;
                <a href="{{route('hasil-ujian.IX-C', $test_id)}}" class="btn btn-primary btn-sm pull-right" style="margin-top: -9px;"><i class="fas fa-file-pdf"></i> IX - C </a>&nbsp;
                <a href="{{route('hasil-ujian.IX-B', $test_id)}}" class="btn btn-primary btn-sm pull-right" style="margin-top: -9px;"><i class="fas fa-file-pdf"></i> IX - B </a>&nbsp;
                <a href="{{route('hasil-ujian.IX-A', $test_id)}}" class="btn btn-primary btn-sm pull-right" style="margin-top: -9px;"><i class="fas fa-file-pdf"></i> IX - A </a>&nbsp;

            </div>
          </div>

          <div id='IX-A' class="datakelas panel-body">
            <div class="col-md-12 alert alert-warning">
              <div class="col-md-6">
                <table class="table table-bordered" style="margin-bottom: 20px">
                  <tbody>
                    <tr>
                      <td>Mata Pelajaran</td>
                      <td>{{$data_a['subject']}}</td>
                    </tr>
                    <tr>
                      <td>Nama Guru</td>
                      <td>{{$data_a['name']}}</td>
                    </tr>
                    <tr>
                      <td>Nama Ujian</td>
                      <td>{{$data_a['subject_test']}}</td>
                    </tr>
                    <tr>
                      <td>Tanggal Ujian</td>
                      <td>{{$data_a['start']}}</td>
                    </tr>
                    <tr>
                      <td>Waktu</td>
                      <td>{{$data_a['time']}} menit</td>
                    </tr>
                  </tbody>
                </table>
              </div>

              <div class="col-md-6">
                <table class="table table-bordered" style="margin-bottom: 20px">
                  <tbody>
                    <tr>
                      <td>Jumlah Soal</td>
                      <td>{{$data_a['num_questions']}}</td>
                    </tr>
                    <tr>
                      <td>Tertinggi</td>
                      <td>{{$data_a['max']}}</td>
                    </tr>
                    <tr>
                      <td>Terendah</td>
                      <td>{{$data_a['min']}}</td>
                    </tr>
                    <tr>
                      <td>Rata-rata</td>
                      <td>{{$data_a['avg']}}</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>

          <!-- Table -->
          <div id class="col-md-12 table-responsive">
            <table id="IX_A-table" class="table table-striped table-bordered table-hover">
              <thead>
                <tr>
                  <th width="30">No</th>
                  <th>Nama Siswa</th>
                  <th>Kelas</th>
                  <th>Jumlah Benar</th>
                  <th>Jumlah Salah</th>
                  <th>Nilai</th>
                  <th>Action</th>
                  </tr>
              </thead>
              @php
                $i=1;
              @endphp
              @foreach ($result['IX_A'] as $IX_A)
                <tr id ="item{{$IX_A->id}}">
                  <td>{{$i}}</td>
                  <td>{{$IX_A->user->name}}</td>
                  <td>{{$IX_A->class}}</td>
                  <td>{{$IX_A->true}}</td>
                  <td>{{$IX_A->false}}</td>
                  <td>{{$IX_A->value}}</td>
                  <td><a onclick="deleteData({{$IX_A->id}})"  class="btn btn-danger btn-xs"><i class="fas fa-times-circle"></i> Batalkan Ujian</a></td>
                </tr>
                @php
                  $i++;
                @endphp
              @endforeach
            </table>
          </div>

        </div>

        @include('results/IX-B')
        @include('results/IX-C')
        @include('results/IX-D')

      </div>
      </div>
      </div>
    </div>
    <br>
   <br>
  <br>
@endsection


@section('script')

    <script type="text/javascript">

    var table = $('#IX_A-table').DataTable({
                    processing: true
                  });

    var table = $('#IX_B-table').DataTable({
                    processing: true
                  });

    var table = $('#IX_C-table').DataTable({
                    processing: true
                  });

    var table = $('#IX_D-table').DataTable({
                    processing: true
                  });


    $('.datakelas').hide();
    $('#IX-A').show(500);


    $("#select_class").on('change', function() {
          if ($(this).val() == 'A'){
            $('.datakelas').hide();
              $('#IX-A').show(500);
          } else if ($(this).val() == 'B') {
            $('.datakelas').hide();
              $('#IX-B').show(500);
          } else if ($(this).val() == 'C') {
            $('.datakelas').hide();
              $('#IX-C').show(500);
          } else {
            $('.datakelas').hide();
              $('#IX-D').show(500);
          }
      });


                    function deleteData(id){
                        var csrf_token = $('meta[name="csrf-token"]').attr('content');
                        swal({
                            title: 'Are you sure?',
                            text: "You won't be able to revert this!",
                            type: 'warning',
                            showCancelButton: true,
                            cancelButtonColor: '#d33',
                            confirmButtonColor: '#3085d6',
                            confirmButtonText: 'Yes, delete it!'
                        }).then(function () {
                            $.ajax({
                                url : "{{ url('hasil-ujian') }}" + '/' + id,
                                type : "POST",
                                data : {'_method' : 'DELETE', '_token' : csrf_token},
                                success : function(data) {
                                  location.reload();
                                    swal({
                                        title: 'Success!',
                                        text: data.message,
                                        type: 'success',
                                        timer: '1500'
                                    })
                                },
                                error : function () {
                                    swal({
                                        title: 'Oops...',
                                        text: data.message,
                                        type: 'error',
                                        timer: '1500'
                                    })
                                }
                            });
                        });
                      }



      </script>
@endsection